### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by rhys-vdw** [mattrobenolt/sourcemap-validator#10]
Not sure if this link will remain live by the time you check this out, but it's causing a 500 (without any more info).

``` url
https://sourcemaps.io/validate?url=https%3A%2F%2Fd3j1vk9m4xbk8a.cloudfront.net%2Fassets%2Fapplication-ca7ebb5e3fcfcadfeb5c-0.js
```

**Comment by kkumler** [comment]
May be getting the same sort of thing here with a large sourcemap, from running locally:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 97, in __call__
    iterable = self.application(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 591, in __call__
    return self.app(environ, start_response)
  File "/usr/src/app/validator/base.py", line 49, in __call__
    response = self.dispatch_request(request)
  File "/usr/src/app/validator/base.py", line 41, in dispatch_request
    return getattr(self, endpoint)(request, **values)
  File "app.py", line 160, in validate_html
    return self.render('report.html', self.validate(request))
  File "app.py", line 181, in validate
    sources = sources_from_index(smap, url)
  File "app.py", line 56, in sources_from_index
    return {make_absolute(index.sources[i]): s.splitlines() for i, s in enumerate(sources)}
  File "app.py", line 56, in <dictcomp>
    return {make_absolute(index.sources[i]): s.splitlines() for i, s in enumerate(sources)}
IndexError: list index out of range
```
